import React from 'react';
import getColors from './colors';
import { Row, Col, Button } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import './gradients.css';

var userColors = [];

const getUserColors = (startIndex = 0, limit = 16) => {
    return userColors.slice(startIndex, startIndex + limit);
}

export default class Gradients extends React.Component {
    constructor(props) {
        super(props);
        this.loadMainColors = this.loadMainColors.bind(this);
        this.loadUserColors = this.loadUserColors.bind(this);
        this.loadMoreMainColors = this.loadMoreMainColors.bind(this);
        this.loadMoreUserColors = this.loadMoreUserColors.bind(this);
        this.pushColors = this.pushColors.bind(this);
        this.loadTime = 1;
        this.state = {
            allColors: [],
            startIndex: 0,
            limitColors: 16,
            mainComponent: true,
        };
        this.initScrollEvent = this.initScrollEvent.bind(this);
        this.loadingHandler = this.loadingHandler.bind(this);
        this.initiateLoading = this.initiateLoading.bind(this);
    }

    initScrollEvent() {
        window.onscroll = () => {
            if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight - 50) {
                if (this.state.mainComponent) {
                    this.loadMoreMainColors();
                } else {
                    this.loadMoreUserColors();
                }
            }
        };
    }

    pushColors(colors) {
        var colorList = [];
        colors.forEach((color, idx) => {
            var key = Object.keys(color)[0];
            var value = JSON.parse(color[key]);
            var element = (<Col xs="12" sm="6" md="3" key={key} style={{padding: "0"}}>
                <div className="gradient-box" style={{background: `linear-gradient(135deg, ${value.color1}, ${value.color2})`, height: "200px"}}>
                    <Button variant="info" className="modify-gradient">
                        <Link to={{ pathname: '/modify', state: { color1: value.color1, color2: value.color2} }} className="modify-link">
                            View / Modify
                        </Link>
                    </Button>
                </div>
            </Col>);
            colorList.push(element);
        });
        this.setState({ allColors: [...this.state.allColors, ...colorList] });
    }

    loadingHandler(colors) {
        if (colors.length === 0) {
            return;
        }
        this.pushColors(colors);
        this.loadTime++;
    }

    loadMoreMainColors() {
        var colors = getColors(this.state.startIndex + this.state.limitColors * this.loadTime, this.state.limitColors);
        this.loadingHandler(colors);
    }

    loadMoreUserColors() {
        var colors = getUserColors(this.state.startIndex + this.state.limitColors * this.loadTime, this.state.limitColors);
        this.loadingHandler(colors);
    }

    loadMainColors() {
        var colors = getColors(this.state.startIndex, this.state.limitColors);
        this.pushColors(colors);
    }

    loadUserColors() {
        userColors = [];
        var colorKeys = Object.keys(localStorage);
        for (var i = 0; i <= colorKeys.length - 1; i++) {
            let key = colorKeys[i];
            let value = localStorage.getItem(key);
            userColors.push({ [key]: value });
        }
        var colors = getUserColors(this.state.startIndex, this.state.limitColors);

        this.pushColors(colors);
    }

    componentWillReceiveProps() {
        window.removeEventListener("scroll", () => {
            if (this.state.mainComponent) {
                this.loadMoreMainColors();
            } else {
                this.loadMoreUserColors();
            }
        });
        
        this.loadTime = 1;

        this.setState({
            allColors: [],
            mainComponent: true
        }, () => {
            this.initiateLoading();
        });
    }

    initiateLoading() {
        if (this.props.location.pathname === "/user-gradients") {
            this.loadUserColors();
            this.setState({ mainComponent: false })
        } else {
            this.loadMainColors();
        }
        this.initScrollEvent();
    }

    componentDidMount() {
        this.initiateLoading();
    }

    render() {
        var heading = this.state.mainComponent ? <h4>Pre-generated Gradients</h4> : <h4>Random Gradients Generated by You</h4>
        return (
            <div className="gradient-wrapper">
                <div className="gradient-row text-center">
                    <div className="gradient-info">
                        {heading}
                        <span>Hover/click on gradients to further modify them</span>
                    </div>
                    <Row>
                        {this.state.allColors}
                    </Row>
                </div>
            </div>
        );
    }
}